from ollama import chat


class AIEngine:

    def analyze(self, event, raw_event, correlation=None):

        mitre = event.get("mitre", {})
        risk = event.get("risk", {})
        windows_event = event.get("windows_event", {})


        correlation_text = (
            str(correlation)
            if correlation
            else "No related events detected."
        )


        prompt = f"""

You are a Senior SOC Analyst working in an enterprise Security Operations Center.

Your task is to analyze Windows Security Events.

Follow these rules strictly:

- Analyze ONLY provided evidence.
- Do not guess.
- Do not invent malware.
- Do not assume attacker activity.
- MITRE ATT&CK mapping represents possible behavior, NOT confirmed attack.
- Risk score is generated by a detection engine and is not proof of compromise.
- If information is missing write "Not Present".
- Normal Windows activity should be classified as Benign.


====================================================
EVENT INFORMATION
====================================================

Event ID:
{event.get("event_id")}

Computer:
{event.get("computer")}

User:
{event.get("account")}

Process:
{event.get("process")}


Windows Event Information:

Title:
{windows_event.get("title","Not Present")}

Description:
{windows_event.get("description","Not Present")}


Risk Score:
{risk.get("score","Not Present")}/100

Severity:
{risk.get("severity","Not Present")}



====================================================
MITRE ATT&CK MAPPING
====================================================

Tactic:
{mitre.get("tactic","Not Present")}

Technique:
{mitre.get("technique","Not Present")}

Technique ID:
{mitre.get("id","Not Present")}



====================================================
CORRELATION INFORMATION
====================================================

{correlation_text}



====================================================
SOC INVESTIGATION REPORT
====================================================


EVENT SUMMARY
====================================================

Event ID:

Risk Score:

Severity:

Windows Description:



MITRE ATT&CK
====================================================

Tactic:

Technique:

Technique ID:



WHY THIS EVENT OCCURRED
====================================================

Explain the likely reason this event occurred.

Only use provided evidence.



IS THIS SUSPICIOUS?
====================================================

Answer:

Benign / Suspicious / Malicious


Reason:

Consider:

BENIGN:
- Normal Windows behavior
- Legitimate system process
- Expected user activity

SUSPICIOUS:
- Unknown process
- Abnormal account activity
- Multiple correlated events
- Unusual behavior

MALICIOUS:
- Confirmed malware
- Known attack indicators
- Clear evidence of compromise



INVESTIGATION STEPS
====================================================

1.

2.

3.



RECOMMENDED ACTIONS
====================================================

1.

2.

3.



INDICATORS OF COMPROMISE
====================================================

User:

Process:

Computer:

Event ID:

IP Address:

Command Line:



SOC ANALYST VERDICT
====================================================

(Benign / Suspicious / Malicious)


"""


        response = chat(
            model="gemma3:4b",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )


        return response["message"]["content"]